# Generated by Django 5.0 on 2024-07-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='CustomUser',
            new_name='user',
        ),
    ]
